language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
env:
  - DSTACK_DB_DSTACK_DATABASE=mysql
  - DSTACK_DB_DSTACK_DATABASE=h2
  - DSTACK_DB_DSTACK_DATABASE=hsqldb
  - DSTACK_DB_DSTACK_DATABASE=postgres
services:
  - redis
before_install: ./tools/build/before.sh
install: 
  - sudo apt-get update
  - sudo apt-get install -y python-libvirt libvirt-dev
  - sudo pip install tox
  - ./tools/build/build.sh
script: ./tools/build/runtests.sh
